### ISSUE TITLE
Completions is not enable to use include methods

### ISSUE THREAD

**Issue by kequeen** [tushortz/Ruby-Completions#4]
Just like this
`require 'rexml/document'
include REXML
Document`
Document is not enable to complete its own methods.Is it possible to do this?

**Comment by tushortz** [comment]
This is a snippet. Although it's possible to do this but this would require
a script. I'm very busy these days and don't see me doing this in the near
future.

A pull request is welcome but as of now, this snippet lacks the
autocomplete feature

**Comment by kequeen** [comment]
I understand what you means.What I want is the tools like ipython,but it's a snippet.Thanks for your answer! I will take a try to create a tool for ruby.
